version: '3'
services:
  # Application Dockerfile is in same folder which is.
  app:
    build: .
    depends_on:
      - db
    environment:
      - DOCKER=true        # ðŸ‘ˆ This tells your Java app it's running inside Docker
    restart: on-failure    # Optional but recommended
    stdin_open: true
    tty: true

  # db is in db folder
  db:
    build: db/.
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: example   # ðŸ‘ˆ Add this line to match your application.properties