services:
  db:
    build: ./db
    container_name: sem-db
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: world

  app:
    build: .
    container_name: sem-app
    depends_on:
      - db
    ports:
      - "8080:8080"


  web:
    build: ./web
    container_name: sem-web
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./web/content:/usr/share/nginx/html:ro
